version: "3"

services:
  app:
    build:
      context: app
      args:
        - firestore_emulator_host=firestore:8812
        - gcloud_project_id=local-project
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./app:/go/src/app
    depends_on:
      - firestore
#  web:
#    build:
#      context: .
#      dockerfile: ./docker/nginx/Dockerfile
#    ports:
#      - 3000:3000
#    command: "npm run dev"
#    volumes:
#      - ./frontend:/work/frontend
  firestore:
    build:
      context: app/firestore
    environment:
      - PROJECT_ID=local-project
    volumes:
      - ./app/firestore:/firestore
    command: /bin/bash /firestore/start.sh
    ports:
      - 8812:8812
  firestore-test:
    build:
      context: app/firestore-test
    environment:
      - PROJECT_ID=test-project
    volumes:
      - ./app/firestore-test:/firestore
    command: /bin/bash /firestore/start.sh
    ports:
      - 8813:8813
