version: "3"

services:
  db:
    restart: always
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: localdb
    volumes: # @TODO gooseをやじめて、init.dに変える
      - ./persistence/init:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8000:8000
    command: "/app/server"
    depends_on:
      - "db"
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 3000:3000
    command: "npm run dev"
    volumes:
      - ./frontend:/work/frontend
