version: "3"

services:
  firestore:
    build:
      context: app/firestore
    environment:
      - PROJECT_ID=test-project-id
    volumes:
      - ./app/firestore:/firestore
    command: /bin/bash /firestore/start.sh
  app:
    build:
      context: ./app
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./app:/go/src/app
#  web:
#    build:
#      context: .
#      dockerfile: ./docker/nginx/Dockerfile
#    ports:
#      - 3000:3000
#    command: "npm run dev"
#    volumes:
#      - ./frontend:/work/frontend
