// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	BookID    string  `json:"book_id"`
	BookTitle *string `json:"book_title"`
	Isbn13    int     `json:"isbn13"`
	UserID    int     `json:"user_id"`
}

type NewBook struct {
	BookTitle *string `json:"book_title"`
	Isbn13    int     `json:"isbn13"`
	UserID    string  `json:"user_id"`
}

type NewUser struct {
	UserName        string `json:"user_name"`
	UserDisplayName string `json:"user_display_name"`
}

type User struct {
	UserID          string `json:"user_id"`
	UserName        string `json:"user_name"`
	UserDisplayName string `json:"user_display_name"`
}
