// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
}
