// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	BookID    string  `json:"book_id"`
	BookTitle *string `json:"book_title"`
	Isbn13    int     `json:"isbn13"`
	OwnerID   int     `json:"owner_id"`
}

type NewBook struct {
	BookTitle *string `json:"book_title"`
	Isbn13    int     `json:"isbn13"`
	OwnerID   int     `json:"owner_id"`
}
